# roles/common/main.yml
---
- name: install common packages
  yum: name={{item}} state=present
  with_items:
    - epel-release
  tags: common

- name: start firewalld
  service: name=firewalld state=started
  tags: common
